ignore:
  - "**/Watchlist"
  - "**/MainActivity"
  - "**/UploadFrag"
  - "**/User"
  - "**/WatchlistAdapter"
  - "**/SwapsFragment"
  - "**/Validation"
  - "**/UserMenu"
  - "**/Search"
  - "**/WatchlistAdapter"
  - "**/UserWatchlist"
  - "**/ViewProduct"
  - "**/ChatFragment"