ignore:
  - "**/UploadFrag"
  - "**/WatchlistAdapter"
  - "**/Validation"
  - "**/Search"
  - "**/UserWatchlist"
  - "**/Register"
  - "**/ChatFragment"
  - "**/CatergoryHomeFragment"
  - "**/UserCatergoryFragment"
  - "**/UploadProduct"
  - "**/Search_Activity"