ignore:
  - "**/UserInfoFragment"               # Converted into UserInfoActivity for testing
  - "**/LoginFrag"                      # Converted into Login_Activity for testing
  - "**/ChatFragment"                   # Converted into Chat_Activity for testing
  - "**/UploadFrag"                     # Converted into UploadProduct for testing
  - "**/CatergoryHomeFragment"
  - "**/UserCatergoryFragment"
  - "**/ViewProduct"                    #problem with testing intents
  - "**/Watchlist"                      #needs userwatchlist object
  - "**/OtherUserProfile"               #product upload null reference
  - "**/OnGoingSwaps"
  - "**/Register"
  - "**/UploadProduct"
  - "**/ChatActivity"
  - "**/Update_Activity"                #needs to test when uploading photo for dp
  - "**/SearchEveryone"
  - "**/Search"
