ignore:
  - "**/UserInfoFragment"               # Converted into UserInfoActivity for testing
  - "**/LoginFrag"                      # Converted into Login_Activity for testing
  - "**/ChatFragment"                   # Converted into Chat_Activity for testing


  -  "**/CatagoryHomeFragment"
  -  "**/UserCatagoryFragment"
